Explicitly remove timeouts from Http client
waldoapp/waldo-go-agent pull request #7
Opened 2023-08-30 19:13 UTC by KhalilBell

2023-08-30 19:47 UTC, eBardX reviewed
Setting the timeout on the client did not produce the desired effect?

2023-08-30 20:08 UTC, KhalilBell commented
> Setting the timeout on the client did not produce the desired effect?

After searching that was the advised way of removing timeouts on client (also I didn't find the same granularity on timeouts on the client)

2023-08-30 20:18 UTC, eBardX requested changes
Please update the agent version in `main.go` to 2.1.1 as well as `CHANGELOG.md`. (Bonus points if you can modify the change log to my satisfaction. 😉)

2023-08-30 20:18 UTC, eBardX commented on upload.go
> +	}
nit: I’m not a big fan of extraneous commas in arrays and structs (like you have on lines 309 and 310).

2023-08-31 21:44 UTC, eBardX commented
So close on the change log! I added a missing link near the end so that the correct tags can be compared.

2023-08-31 21:45 UTC, eBardX approved these changes

2023-08-31 21:46 UTC, merged